# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('tipo', models.IntegerField(default=0)),
                ('fecha_creacion', models.CharField(max_length=128)),
                ('hora_creacion', models.CharField(max_length=128)),
                ('recurso', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('codido_creador', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apuntes_compartidos', models.ManyToManyField(blank=True, related_name='compartidos', to='temporio_web.Apunte')),
                ('apuntes_favoritos', models.ManyToManyField(blank=True, related_name='favoritos', to='temporio_web.Apunte')),
                ('materias', models.ManyToManyField(blank=True, related_name='_estudiante_materias_+', to='temporio_web.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo', models.CharField(max_length=20, unique=True)),
                ('nombre_materia', models.CharField(max_length=128)),
                ('estudiantes', models.ManyToManyField(to='temporio_web.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.CharField(max_length=10)),
                ('hora_inicio', models.CharField(max_length=10)),
                ('hora_fin', models.CharField(max_length=10)),
                ('dia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=128)),
                ('fecha_alarma', models.DateField()),
                ('tiempo_alarma', models.DateTimeField()),
                ('tipo_repeticion', models.CharField(max_length=20)),
                ('tipo_tarea', models.IntegerField(default=0)),
                ('materia', models.CharField(max_length=128)),
                ('grupo_materia', models.CharField(max_length=128)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('grupos', models.ManyToManyField(blank=True, related_name='_profesor_grupos_+', to='temporio_web.Profesor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario',
            field=models.ManyToManyField(to='temporio_web.Horario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporio_web.Profesor'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='notificaciones_propias',
            field=models.ManyToManyField(blank=True, related_name='notificaciones', to='temporio_web.Notificacion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
