# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporio_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='str_fecha',
            field=models.CharField(default='2016-7-1-7:00', max_length=128),
            preserve_default=False,
        ),
    ]
