# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporio_web', '0002_auto_20161103_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_horario_materia', to='temporio_web.CodigoGrupo'),
        ),
    ]
